#!/usr/bin/env bash

################################################################################
# Script name: obj  Version 1.5.0.1
# This script is a part of "bash-object" project.
# https://github.com/pkochis/bash-object
# "bash-object" scripts are licensed under the GNU General Public License v3.0
# author: pal@kochis.hu
#
# A) Common routine: objRparentPath
# B) Get obj's home directory
# C) Loader: obj, objRrestart
#
# Reserved words: obj* OBJ* this* THIS* --help
################################################################################

# A) Common routine: objRcallerScript
objRcallerScript() { local i p
 for ((i=0; i<${#FUNCNAME[@]}; i++)); do
  [[ ${FUNCNAME[$i]} != @(source|main) ]] && continue;
  p="${BASH_SOURCE[$i]%/*}"; [[ $p == ${BASH_SOURCE[$i]} ]] && p="."; [[ -z $p ]] && p="/"; cd "$p"; pwd; cd "$OLDPWD"; return
 done
 return 1
}; export -f objRcallerScript

# B) Get real name of obj's home directory
obj_HOME="$(objRcallerScript)"; export obj_HOME obj_INIT="${obj_HOME}/init"

# C) Loader
objRrestart() { source "${obj_INIT}" && [[ -n $1 ]] && obj "$@"; }
obj() { objRrestart "$@"; }
export -f objRrestart obj

(($# > 0)) && objRrestart "$@"
