#!/usr/bin/env bash

################################################################################
# Script name: obj-classes  Version 1.5
# This script is a part of "bash-object" project.
# https://github.com/pkochis/bash-object
# "bash-object" scripts are licensed under the GNU General Public License v3.0
# author: pal@kochis.hu
#
# A) @obj@info and obj-info
# B) @obj@dictionary and obj-error-messages
# C) Change error helper
# D) @obj@backup-variables
################################################################################
[[ $(type -t objCconstruct) != function ]] && exit  # prevents unwanted load

# A) @obj@info and obj-info
((${objects["ID@obj@info"]:-0} == 0)) && obj @obj obj-create @info \
 objC_Public info '{ local i
  [[ -z $1 ]] && for i in "${!objects[@]}"; do [[ $i == @(ID|ID*\ *) ]] && echo \"${i#ID}\" || { [[ $i == ID* ]] && echo ${i#ID}; }; done
  [[ -n $1 && ${objects["ID$1"]:-0} -gt 0 ]] && {
   o=${objects["ID$1"]}; declare -n do=obj_details${objects["ID$1"]} vo=obj_data${objects["ID$1"]}
   [[ $1 != @* ]] && {
    echo -e "\nObject: ${1}\nClass:  ${do[parent]}\n"
    echo -e " Default method: ${do[D]}\n Init method:     ${do[I]}"
    echo -en " Help file:      "; [[ -n ${do[H]} ]] && echo "${do[H]}.help" || echo ""
   }
   [[ $1 == @* ]] && { echo -e "\nClass:  ${1}\nParent: ${do[parent]}"; }
   echo -e "\n Public methods:"; for i in "${!do[@]}"; do [[ $i == P* ]] && echo "  ${i:1} (objR${do[$i]})"; done
   [[ $1 != @* ]] && {
    echo -e "\n Private methods:"; for i in "${!d[@]}"; do [[ $i == M* && -z ${d["P${i:1}"]} ]] && echo "  ${i:1} (objR${d[$i]})"; done
    echo -e "\n Variables:"; for i in "${!vo[@]}"; do echo "  ${i:1} (objV_${vo[$i]})"; done
   }
   [[ $1 == @* ]] && {
    echo -e "\n\nStored data for objects:"; declare -n dc=obj_DETAILS${objects["ID$1"]} vc=obj_DATA${objects["ID$1"]}
    echo -e "\n Default method: ${dc[D]}\n Init method:    ${dc[I]}"
    echo -en " Help file:      "; [[ -n ${do[H]} ]] && echo "${do[H]}.help" || echo ""
    echo -e "\n Public methods:"; for i in "${!dc[@]}"; do [[ $i == P* ]] && echo "  ${i:1} (objR${dc[$i]})"; done
    echo -e "\n Private methods:"; for i in "${!dc[@]}"; do [[ $i == M* && -z ${dc["P${i:1}"]} ]] && echo "  ${i:1} (objR${dc[$i]})"; done
    echo -e "\n Variables:"; for i in "${!vc[@]}"; do echo "  ${vc[$i]%% *} ${i:1} ${vc[$i]#* }"; done
   }
  }
 }' objC_Default info
((${objects["IDobj-info"]:-0} == 0)) && obj @obj@info obj-create obj-info

# B) @obj@dictionary and obj-error-messages
((${objects["ID@obj@dictionary"]:-0} == 0)) && obj @obj obj-create @dictionary \
 objC_Variable -gA 'obj_dictionary=()' \
 objC_Public translate '{ echo "${obj_dictionary["$1"]:-$1}"; }' \
 objC_Default translate \
 objC_Private obj-add-local-dictionary '{
  local f="$(objRlocalisedFile "$(objRcallerScript)" "${this[1]}.dict")" what=" "; [[ -f $f ]] && {
   while IFS= read -r; do
    [[ $REPLY == From:\ * ]] && what="${REPLY#From: }"; [[ $REPLY == To:\ * ]] && { obj_dictionary+=(["$what"]="${REPLY#To: }"); what=" "; }
   done < "$f";
  } 
 }' \
 objC_Init obj-add-local-dictionary
((${objects["IDobj-error"]:-0} == 0)) && obj @obj@dictionary obj-create obj-error

# C) Change error helper
objError() { local i c=0 et="$(obj obj-error translate "$1")"; shift; for i in "$@"; do ((c++)); et="${et//%A${c}%/$i}"; done; echo "$et"; }

# D) @obj@backup-variables
((${objects["ID@obj@backup-variables"]:-0} == 0)) && obj @obj obj-create @backup-variables \
 objC_Variable -g obj_backupfile="" \
 objC_Public obj-restore '{ local i; : ${obj_backupfile:="$(objRcallerScript)/${this[1]}.bak"}
  [[ -e ${obj_backupfile} ]] && while IFS= read -r; do
   for i in "${!this_data[@]}"; do [[ $REPLY == ${i:1}=* ]] && eval "$REPLY"; done
  done < "${obj_backupfile}"
 }' \
 objC_Public obj-backup '{ local i w; : ${obj_backupfile:="$(objRcallerScript)/${this[1]}.bak"}
  echo -n "" > "${obj_backupfile}"
  for i in "${!this_data[@]}"; do w="$(declare -p objV_${this_data[$i]})"; echo "${i:1}=${w#*=}" >> "${obj_backupfile}"; done  
 }' \
 objC_Public i @obj@info obj-info \
 objC_Default obj-restore \
 objC_Init obj-restore
